### ISSUE TITLE
GUI in the TympanRemote App

### ISSUE THREAD

**Issue by yuan9778** [Tympan/Docs#2]
This is more a question than an issue. 

I used JSON object to generate GUI on Android and it works great for buttons. However, I wonder how to display a changing number on android app. For example, for Gain Seetings (high, mid, low)，I want to know current gain for high and display it on the screen.  Every time I touch ~+, the current gain changes accordingly. 

Thanks much in advance.

Sanqing

**Comment by kxm-creare** [comment]
Absolutely you can do this.  Can you post how you create your JSON object, or the relevant parts of it?  We've recently added some helper functions to help create the JSON object, and my response on how to do it will depend on how you're creating the JSON itself.

**Comment by yuan9778** [comment]
I edited this source code file trying to generate a GUI for adjusting gain on Android :
[https://github.com/Tympan/Tympan_Library/blob/master/examples/05-FullSystems/WDRC_8BandFIR/SerialManager.h](url)

I created the JSON as follows:

```
case 'J':
	{
		char jsonConfig[] = "JSON={"
		"'pages':["
			"{'title':'Bands Gain','cards':["
			  "{'name':'Band1 (0Hz)','buttons':[{'label': 'less', 'cmd': '!'},{'label': 'more', 'cmd': '1'}],'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[0]}},"
			  "{'name':'Band2 (317Hz)','buttons':[{'label': 'less', 'cmd': '@'},{'label': 'more', 'cmd': '2'}],'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[1]}},"
			  "{'name':'Band3 (503Hz)','buttons':[{'label': 'less', 'cmd': '#'},{'label': 'more', 'cmd': '3'}],'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[2]}},"
			  "{'name':'Band4 (798Hz)','buttons':[{'label': 'less', 'cmd': '$'},{'label': 'more', 'cmd': '4'}],'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[3]}},"
			  "{'name':'Band5 (1265Hz)','buttons':[{'label': 'less', 'cmd': '%'},{'label': 'more', 'cmd': '5'},'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[4]}]},"
			  "{'name':'Band6 (2006Hz)','buttons':[{'label': 'less', 'cmd': '^'},{'label': 'more', 'cmd': '6'},'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[5]}]},"
			  "{'name':'Band7 (3281Hz)','buttons':[{'label': 'less', 'cmd': '&'},{'label': 'more', 'cmd': '7'},'inuts':{'label': 'current gain', 'type': 'float', 'value': gainChanged[6]}]},"
			  "{'name':'Band8 (5045Hz)','buttons':[{'label': 'less', 'cmd': '*'},{'label': 'more', 'cmd': '8'},'inputs':{'label': 'current gain', 'type': 'float', 'value': gainChanged[7]}]}"
			"]},"	
		  "]"		  
		  
		"}";
		myTympan.println(jsonConfig);
		delay(50);
		break;
	}
```

 
gainChanged is a float array defined at Line 43 in source code file like this:
` float gainChanged[8] = {0,0,0,0,0,0,0,0};`

Its value is updated once a button is pushed like this:
```
  case '1':
      incrementChannelGain(1-1, channelGainIncrement_dB); 
      gainChanged[0] += channelGainIncrement_dB;
      break;
```

It doesn't work because gainChanged is not recognized and cause an error.

Looking forward to your reply and thanks much for your time!

**Comment by yuan9778** [comment]
Dear Kenneth,

I posted more details regarding my problem. I really look forward to your reply. 

Best regards,
Sanqing

**Comment by wheresaddie** [comment]
@kxm-creare please see the posted error logs above :)

**Comment by kxm-creare** [comment]
@yuan9778 a few comments:

1.  What you're creating in the JSON is a string, not code per se.  That's why each line begins and ends with double-quotes.  So where you put, for example, `gainChanged[3]`, that's not a float value, it's really a string (but not even a valid string because it isn't in quotes).  That will give you errors.  A valid JSON string for that part would look something like: `'type': 'float', 'value': 0`

2.  It looks like you have a few other syntax errors in this string.  We have implemented a new tool for creating JSON strings without the syntax errors (see for example https://github.com/Tympan/Tympan_Library/commit/f01ee59926a552a4c714214ffdd88fb157a797a0), but it isn't as capable as the direct json string writing like you're doing.  My favorite way to debug a jsonConfig string is to print the jsonConfig in the serial monitor, and then copy-paste it into one of the many free json validators available online.  To print the JSON to the serial monitor, add these lines to your code after you define jsonConfig:

```
  Serial.println("My JSON config, in proper JSON style with double quotes instead of single quotes:");
  Serial.println(String(jsonConfig).remove(0,5).replace("'","\""));
```

(note I had to add a bit of code to replace all the single quotation marks with double quotation marks, in order to conform to the JSON spec).  Then, program your Tympan, open the Arduino Serial Monitor, send J to your Tympan, and copy the resulting JSON string from the serial monitor.  If you paste that string from the serial monitor into https://jsonlint.com/?code=, you'll see there are errors with matching opening/closing brackets.

3.  In order to get numbers displayed, I recommend following this example: https://github.com/Tympan/Tympan_Sandbox/blob/master/WDRC_3Band_Stereo_BTaudio_App/SerialManager.h#L552-L554.  Note that a separate function is called to update the middle "buttons" that show the number,  e.g. `setButtonText("highGain",channelGainAsString(3-1));`.  So you'd want something like:

```

char jsonConfig[] = "JSON={"
    "'pages':["
      "{'title':'Bands Gain','cards':["
        "{'name':'Band1 (0Hz)','buttons':[{'label': 'less', 'cmd': '!','width':4},{'label': '', 'id': 'gain0','width':4},{'label': 'more', 'cmd': '1','width':4}]},"
        "{'name':'Band2 (317Hz)','buttons':[{'label': 'less', 'cmd': '@','width':4},{'label': '', 'id': 'gain1','width':4},{'label': 'more', 'cmd': '2','width':4}]},"
        "{'name':'Band3 (503Hz)','buttons':[{'label': 'less', 'cmd': '#','width':4},{'label': '', 'id': 'gain2','width':4},{'label': 'more', 'cmd': '3','width':4}]},"
        "{'name':'Band4 (798Hz)','buttons':[{'label': 'less', 'cmd': '$','width':4},{'label': '', 'id': 'gain3','width':4},{'label': 'more', 'cmd': '4','width':4}]},"
        "{'name':'Band5 (1265Hz)','buttons':[{'label': 'less', 'cmd': '%','width':4},{'label': '', 'id': 'gain4','width':4},{'label': 'more', 'cmd': '5','width':4}]},"
        "{'name':'Band6 (2006Hz)','buttons':[{'label': 'less', 'cmd': '^','width':4},{'label': '', 'id': 'gain5','width':4},{'label': 'more', 'cmd': '6','width':4}]},"
        "{'name':'Band7 (3281Hz)','buttons':[{'label': 'less', 'cmd': '&','width':4},{'label': '', 'id': 'gain6','width':4},{'label': 'more', 'cmd': '7','width':4}]},"
        "{'name':'Band8 (5045Hz)','buttons':[{'label': 'less', 'cmd': '*','width':4},{'label': '', 'id': 'gain7','width':4},{'label': 'more', 'cmd': '8','width':4}]}"
      "]}"
      "]"
    "}";
```

And then make sure to update the number in your code using a function like `setButtonText`.  Note that when you open the app, there will be no text in there since the json string had a label of '' for each middle button.  Thus I recommend either sending a default, e.g. 'label':'4.0', or do what the previously-linked sketch did and send the values right after you send the json: https://github.com/Tympan/Tympan_Sandbox/blob/master/WDRC_3Band_Stereo_BTaudio_App/SerialManager.h#L412-L416

**Comment by yuan9778** [comment]
It works!

I'm quite interested in Tympan and  might have more questions in the future.

Thanks so much for your time!

Sanqing
